export interface ParticipantDiary {
    id?:string,
    profileDOB: string,
    profileName: string,
    surveyId: string,
    participantId: string,
    formType: string,
    // Event
    healthEvent?: number,
    healthEventSpecification?: string,
    onsetDate?: string,
    endDate?: string,
    ongoingStatus?: number,
    descriptionData?: string,
    outcome?: number,
    outcomeSpecification?: string,
    eventTreatment?: number,
    postEventTreatment?: number,
    // Dr Visit
    assessers?: number[],
    assesserText?: string,
    GMFCScore?: string,
    GMFCType?: number,
    eventDate?: string,
    redirect?: boolean,
    visitReason?: string,
    prescription?: number,
    device?: number[],
    // Withdrawl
    withdrawalDate?: string,
    withdrawalReason?: string,
    org: string,
    dateWritten: string,
    userId: string,
    profileId: string,
}
