//Action types. Consts used as action types throughout the
//project.
//**************redux/actions/Authentication.js********************
// Related to user login and authentication

export const USERS_META_DATA = 'USERS_META_DATA';
export const USERS_CREATE_SUCCESS = 'USERS_CREATE_SUCCESS';
export const USERS_CREATE_FAILED = 'USERS_CREATE_FAILED';
export const USERS_LOGIN_DISABLED_ERROR = 'USERS_LOGIN_DISABLED_ERROR';
export const USERS_LOGIN_ERROR = 'USERS_LOGIN_ERROR';
export const USERS_LOGOUT = 'USERS_LOGOUT';
export const USERS_PASSWORD_RESET = 'USERS_PASSWORD_RESET';
export const USERS_PASSWORD_CHANGE_SUCCESS = 'USERS_PASSWORD_CHANGE_SUCCESS';
export const USERS_PASSWORD_RESET_SUCCESS = 'USERS_PASSWORD_RESET_SUCCESS';
export const USERS_PASSWORD_CHANGE_FAIL = 'USERS_PASSWORD_CHANGE_FAIL';
export const USERS_EMAIL_VERIFICATION_SUCCESS = 'USERS_EMAIL_VERIFICATION_SUCCESS';
export const USERS_EMAIL_VERIFICATION_FAIL = 'USERS_EMAIL_VERIFICATION_FAIL';
export const USERS_PASSWORD_RESET_FAIL = 'USERS_PASSWORD_RESET_FAIL';
export const USERS_RESET_STATE = 'USERS_RESET_STATE';
export const USERS_EMAIL_VERIFICATION_RESEND_SUCCESS = 'USERS_EMAIL_VERIFICATION_RESEND_SUCCESS';
export const USERS_EMAIL_VERIFICATION_RESEND_FAIL = 'USERS_EMAIL_VERIFICATION_RESEND_FAIL';
export const USERS_RESET_AUTH_ERROR = 'USERS_RESET_AUTH_ERROR';
export const USERS_EMAIL_VERIFICATION_RESET = 'USERS_EMAIL_VERIFICATION_RESET';
export const SET_PREVIEW_MODE = 'SET_PREVIEW_MODE';
export const SET_SHOW_TABS = 'SET_SHOW_TABS';
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const SET_PREVIEW_ORG = 'SET_PREVIEW_ORG';
export const SET_ORG = 'SET_ORG';
export const SET_Q13_VIEW = 'SET_Q13_VIEW';
export const RESET_ORG = 'RESET_ORG';
export const SET_ORGS = 'SET_ORGS';
export const SELECT_ORG = 'SELECT_ORG';
export const PUBLIC_SURVEYS = 'PUBLIC_SURVEYS';
export const SELECT_PUBLIC_SURVEY = 'SELECT_PUBLIC_SURVEY';
export const RESET_PUBLIC_SURVEY = 'RESET_PUBLIC_SURVEY';

// Authentication.js
export const IS_LOADING = 'IS_LOADING';

//**************redux/actions/Participant.js********************
export const ACTIVE_PARTICIPANT = 'ACTIVE_PARTICIPANT';
export const ADD_PARTICIPANT_NAMES = 'ADD_PARTICIPANT_NAMES';
export const REMOVE_PARTICIPANT_NAMES = 'REMOVE_PARTICIPANT_NAMES';
export const PARTICIPANT_LOOKUP_FAILED = 'PARTICIPANT_LOOKUP_FAILED';
export const PARTICIPANT_LOOKUP_RESET = 'PARTICIPANT_LOOKUP_RESET';
export const PARTICIPANT_ALREADY_REGISTERED = 'PARTICIPANT_ALREADY_REGISTERED';
export const PARTICIPANT_CANCELED = 'PARTICIPANT_CANCELED';
export const PARTICIPANT_REMOVE = 'PARTICIPANT_REMOVE';
export const UPDATE_PARTICIPANT = 'UPDATE_PARTICIPANT';
export const PARTICIPANT_INBOX = 'PARTICIPANT_INBOX';
export const GET_EHR_RECEIPTS = 'GET_EHR_RECEIPTS';

//**************redux/actions/Questionnaire.js********************
export const Q13_ANSWER = 'Q13_ANSWER';
export const Q13_ANSWERS_FROM_COLLECTION = 'Q13_ANSWERS_FROM_COLLECTION';
export const Q13_RESET = 'Q13_RESET';
export const Q13_QUERY = 'Q13_QUERY';
export const Q13_QUERY_RESET = 'Q13_QUERY_RESET';
export const Q13_STACK_PUSH = 'Q13_STACK_PUSH';
export const Q13_STACK_POP = 'Q13_STACK_POP';
export const Q13_ANSWER_QUERY = 'Q13_ANSWER_QUERY';
export const Q13_ANSWER_WRITE = 'Q13_ANSWER_WRITE';
export const Q13_RESPONSE_RESET = 'Q13_RESPONSE_RESET';
export const SURVEY_QUERY = 'SURVEY_QUERY';
export const SURVEY_RESET = 'SURVEY_RESET';
export const SURVEY_INFORMED_CONSENT = 'SURVEY_INFORMED_CONSENT';
export const SURVEY_INFORMED_CONSENT_AGREED = 'SURVEY_INFORMED_CONSENT_AGREED';
export const SURVEY_INFORMED_CONSENT_RESET = 'SURVEY_INFORMED_CONSENT_RESET';
export const APPLICATION_READY = 'APPLICATION_READY';
export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE';
export const CLEAR_ACTIVE_PROFILE = 'CLEAR_ACTIVE_PROFILE';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';

// ************** redux/actions/Diary.js ***************************
export const SET_DIARY_AVAILABILITY = 'SET_DIARY_AVAILABILITY';
export const SUBMIT_DIARY = 'SUBMIT_DIARY';
export const GET_DIARY_ENTRIES = 'GET_DIARY_ENTRIES';

// ************** redux/actions/Ehr.js ***************************
export const SET_EHR_ACCOUNTID = 'SET_EHR_ACCOUNTID';
export const SET_EHR_ACCESSCODE = 'SET_EHR_ACCESSCODE';
export const SET_EHR_BEARER_TOKEN = 'SET_EHR_BEARER_TOKEN';
export const SET_EHR_ERROR = 'SET_EHR_ERROR';
export const SET_EHR_SEARCH_RESULT = 'SET_EHR_SEARCH_RESULT';
export const SET_EHR_SELECTED = 'SET_EHR_SELECTED';
export const SET_EHR_PATIENT = 'SET_EHR_PATIENT';
export const SET_EHR_RECORD = 'SET_EHR_RECORD';
export const SET_EHR_LINK_SUCCESS = 'SET_EHR_LINK_SUCCESS';
export const RESET_EHR_STATE = 'RESET_EHR_STATE';
export const RESET_EHR_SEARCH = 'RESET_EHR_SEARCH';
